apiVersion: v1
kind: Pod
metadata:
  name: envvars-multiple-secrets
spec:
  containers:
  - name: envars-test-container
    image: nginx
    env:
    - name: BACKEND_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: USER_NAME
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: PASSWORD